# Generated by Django 5.2.1 on 2025-07-23 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_remove_keyword_domain_userprofileinfo_delete_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, verbose_name='域名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL, verbose_name='所屬使用者')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=255, verbose_name='關鍵字')),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='ranking.domain', verbose_name='所屬域名')),
            ],
            options={
                'verbose_name': '關鍵字',
                'verbose_name_plural': '關鍵字',
            },
        ),
        migrations.CreateModel(
            name='KeywordRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('keyword_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='ranking.keyword', verbose_name='所屬關鍵字')),
            ],
            options={
                'verbose_name': '關鍵字排名歷史',
                'verbose_name_plural': '關鍵字排名歷史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['user', 'domain_name'], name='ranking_dom_user_id_8b1257_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('user', 'domain_name')},
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['domain_name', 'keyword_name'], name='ranking_key_domain__575bca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('domain_name', 'keyword_name')},
        ),
        migrations.AddIndex(
            model_name='keywordrankhistory',
            index=models.Index(fields=['keyword_name', 'created_at'], name='ranking_key_keyword_6a8a13_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrankhistory',
            index=models.Index(fields=['created_at'], name='ranking_key_created_bffcf4_idx'),
        ),
    ]
